# Generated by Django 6.0.3 on 2026-03-23 05:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('category', models.CharField(choices=[('ALL', 'All Categories'), ('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transportation'), ('OFFICE', 'Office Supplies'), ('UTILITIES', 'Utilities'), ('SALARY', 'Salary & Wages'), ('RENT', 'Rent'), ('MARKETING', 'Marketing'), ('OTHER', 'Other')], default='ALL', max_length=20)),
                ('alert_threshold', models.IntegerField(default=80, help_text='Percentage at which to trigger alert (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='organizations.organization')),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('THRESHOLD', 'Threshold Reached'), ('EXCEEDED', 'Budget Exceeded')], max_length=10)),
                ('percentage', models.IntegerField()),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgets.budget')),
            ],
            options={
                'db_table': 'budget_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
