# Generated by Django 6.0.3 on 2026-06-10 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('organizations', '0004_invitation_inv_email_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['organization', 'is_active', 'category'], name='bud_org_act_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['organization', 'is_active', 'start_date', 'end_date'], name='bud_org_act_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['budget', 'alert_type'], name='bud_alert_type_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['is_read', '-created_at'], name='bud_alert_read_dt_idx'),
        ),
    ]
