# Generated by Django 6.0.3 on 2026-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_bud_org_act_cat_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('ALL', 'All Categories'), ('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transportation'), ('TRAVEL', 'Travel & Accommodation'), ('OFFICE', 'Office Supplies'), ('UTILITIES', 'Utilities'), ('SALARY', 'Salary & Wages'), ('RENT', 'Rent'), ('MARKETING', 'Marketing & Advertising'), ('OTHER', 'Other')], default='ALL', max_length=20),
        ),
    ]
