# Generated by Django 6.0.3 on 2026-05-01 06:07

from django.db import migrations, models


def convert_managers_to_owners(apps, schema_editor):
    """Convert all MANAGER roles to OWNER"""
    OrganizationMember = apps.get_model('organizations', 'OrganizationMember')
    Invitation = apps.get_model('organizations', 'Invitation')
    
    # Update all members with MANAGER role to OWNER
    OrganizationMember.objects.filter(role='MANAGER').update(role='OWNER')
    
    # Update all pending invitations with MANAGER role to OWNER
    Invitation.objects.filter(role='MANAGER').update(role='OWNER')


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        # First, run the data migration to convert MANAGER to OWNER
        migrations.RunPython(convert_managers_to_owners, migrations.RunPython.noop),
        
        # Then alter the field choices to remove MANAGER
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('STAFF', 'Staff')], max_length=10),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('STAFF', 'Staff')], max_length=10),
        ),
    ]
