# Generated by Django 6.0.3 on 2026-06-10 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_membership_single_org_invitation_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email', 'status', 'is_used', 'expires_at'], name='inv_email_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['organization', 'status', 'is_used'], name='inv_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'role'], name='mem_org_role_idx'),
        ),
    ]
