# Generated by Django 6.0.3 on 2026-03-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_organization_alter_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
