# Generated by Django 6.0.3 on 2026-06-10 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_vendor'),
        ('organizations', '0004_invitation_inv_email_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'status', 'date'], name='exp_org_stat_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'organization', 'status', 'date'], name='exp_user_org_st_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'category', 'status', 'date'], name='exp_org_cat_st_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['organization', 'vendor'], name='exp_org_vendor_idx'),
        ),
    ]
