# Generated by Django 6.0.3 on 2026-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_rejection_reason_expense_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food & Dining'), ('TRANSPORT', 'Transportation'), ('TRAVEL', 'Travel & Accommodation'), ('OFFICE', 'Office Supplies'), ('UTILITIES', 'Utilities'), ('SALARY', 'Salary & Wages'), ('RENT', 'Rent'), ('MARKETING', 'Marketing & Advertising'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
