# Generated by Django 6.0.3 on 2026-03-24 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0003_expense_vendor'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/%Y/%m/')),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('vendor_confidence', models.IntegerField(default=0)),
                ('amount_confidence', models.IntegerField(default=0)),
                ('date_confidence', models.IntegerField(default=0)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt', to='expenses.expense')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='receipts_created_8c6a99_idx'), models.Index(fields=['organization', '-created_at'], name='receipts_organiz_135a41_idx'), models.Index(fields=['status'], name='receipts_status_7da223_idx')],
            },
        ),
    ]
