# Generated by Django 4.2.11 on 2026-04-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
