# Generated by Django 6.0.3 on 2026-06-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipt_category_receipt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='ocr_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ocr_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ocr_validation_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
