# Generated by Django 6.0.3 on 2026-03-24 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('EXPENSE_CREATED', 'Expense Created'), ('EXPENSE_UPDATED', 'Expense Updated'), ('EXPENSE_DELETED', 'Expense Deleted'), ('EXPENSE_APPROVED', 'Expense Approved'), ('EXPENSE_REJECTED', 'Expense Rejected'), ('BUDGET_CREATED', 'Budget Created'), ('BUDGET_UPDATED', 'Budget Updated'), ('BUDGET_DELETED', 'Budget Deleted'), ('MEMBER_INVITED', 'Member Invited'), ('MEMBER_JOINED', 'Member Joined'), ('ROLE_CHANGED', 'Role Changed'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='activity_lo_timesta_c26c07_idx'), models.Index(fields=['organization', '-timestamp'], name='activity_lo_organiz_baea97_idx'), models.Index(fields=['action_type'], name='activity_lo_action__2e2c8b_idx')],
            },
        ),
    ]
