# Generated by Django 6.0.3 on 2026-06-10 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
        ('organizations', '0004_invitation_inv_email_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['organization', 'action_type', '-timestamp'], name='act_org_action_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['organization', 'user', '-timestamp'], name='act_org_user_ts_idx'),
        ),
    ]
