# Generated by Django 6.0.3 on 2026-03-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_currency',
            field=models.CharField(choices=[('NPR', 'रू (NPR)'), ('USD', '$ (USD)'), ('EUR', '€ (EUR)')], default='NPR', help_text='Preferred currency for display', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='items_per_page',
            field=models.IntegerField(default=10, help_text='Number of items to display per page in tables'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', help_text='UI theme preference', max_length=10),
        ),
    ]
