# Generated by Django 6.0.3 on 2026-06-07 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_manager_role'),
        ('users', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_organization',
            field=models.ForeignKey(blank=True, help_text='Currently selected workspace organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='organizations.organization'),
        ),
    ]
